### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by GrzegorzRybkowski** [dobrapyra/PotatoScroll#1]
It's not working on macOS, video with the behaviour below:

https://i.imgur.com/taEpDtU.mp4

**Comment by dobrapyra** [comment]
Thanks for feedback about behaviour on macOS.
I have already started changes for better handling of touch devices and adding a `forceCustom` flag.
I think this is a related issue and the latest changes will improve the behavior on macOS too.
